// Import fonts from Google (Next.js 13)
import { Inter, Roboto } from "next/font/google";
import "./globals.css";

// Add font imports for Inter and Roboto with valid weights
const inter = Inter({
  variable: "--font-inter", // Custom CSS variable for the font
  subsets: ["latin"], // Load the latin subset
});

const roboto = Roboto({
  variable: "--font-roboto", // Custom CSS variable for the monospaced font
  subsets: ["latin"], // Latin subset
  weight: ["400", "700"], // Available weights for Roboto
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
